/**
 * Modifies the Jest's Expect error message for display in the IDE
 *
 * @param {Error} error Error, generated by Jest's Expect
 * @param {String} errorMessage An error message that will be displayed to the user in the IDE
 * @param {Boolean} rmStack Specifies whether stack trace errors will be deleted
  */
function customizeError(error, errorMessage, rmStack = false) {
    error.message = error.message.replace(/.*\n/, errorMessage);
    if (rmStack) {
        error.stack = null;
    }
}

// TODO: rename import_variable to importByName after all merges
/**
 * Workaround for easier handling errors in importing variables from rewired modules
 *
 * @param {object} rewired_module Rewired module from which you want to import a variable
 * @param {String} variable_name Variable name to be imported
 *
 * @return "variable_name" value
 *
 * @throws {Error} user-readable error if it was impossible to import a variable with that name
 */
function import_variable(rewired_module, variable_name){
    try {
        return rewired_module.__get__(variable_name);
    }
    catch (e) {
        let errorToShow = new Error(`Checkout that name ${variable_name} is defined in the ${rewired_module.__get__('module.filename').split('/').pop()}`);
        errorToShow.stack = null;
        throw errorToShow;
    }
}
